### PR TITLE
fix(tray): svg's did not load

### LINKED ISSUE #1221: Tray: SVG icons do not load
**Describe the bug**

Applications that use an SVG (or perhaps other local path based images) instead of a symbolic name seem to fallback to the disconnected icon.

Using the already existing image provider helps in fixing this issue: https://github.com/JakeStanger/ironbar/compare/master...MagneFire:fix/tray-use-picture?expand=1. But I couldn't get this to work for the `Update` event.

**To reproduce**

1. Ensure the tray module is enabled
2. Install an app that uses SVGs like ProtonApp (`paru -S proton-vpn-gtk-app`)
3. Observe the disconnected icon

**Expected behavior**

**System information:**
- Distro: Arch Linux
- Compositor: Sway
- Ironbar version: git-2159aac

**Configuration**

<details><summary>Config</summary>

```
let {
    $tray = {
        type = "tray"
        class = "module module-tray"
        icon_size = 24
        direction = "h"
    }
}


in {
    position = "top"
    height = 1
    layer = "top"
    icon_theme = "Papirus"

    start = [  ]
    center = [ $tray ]
    end = [ ]
}

```

</details>

**Screenshots**

Image

### LINKED ISSUE #1442: allow theming of tray icons
in waybar, there is an option to [theme tray icons](https://github.com/Alexays/Waybar/wiki/Module:-Tray) that is not present in this bar.
`icon_overrides` can theme the launcher module, why can't it theme the tray too? maybe separate configurations for each?

example from my waybar config (left to right: steam, bluemail, legcord)
Image

### PR DESCRIPTION
**Pull request by pancakedevourer**
SVG icons couldn't load in the tray before, and showed a disconnected icon.

Fixes #1221
Resolves #1442

### CODE REVIEW

**Comment by JakeStanger** [comment]
Thanks for this. I think this somewhat duplicates the logic in `tray::icon` (or really, that duplicates the logic here).

https://github.com/JakeStanger/ironbar/blob/83e872885924f5c53d8c42791451c59632e9ec4a/src/modules/tray/icon.rs#L26C4-L26C28

Are you able to have a look and see if there's any opportunity to clear that up a bit please? Ideally we'd have one path through.

**Comment by pancakedevourer** [comment]
Sorry for the holdup, cleaned it up. Logic is in icon.rs now

**Comment by JakeStanger** [comment]
Thanks. Can you have a look at the failing build please?

**Comment by pancakedevourer** [comment]
Whoops, fixed it

File: src/modules/tray/mod.rs [hunk 1]
```diff
@@ -1,29 +1,29 @@
...
 use interface::TrayMenu;
 use serde::Deserialize;
 use std::collections::HashMap;
+use std::path::PathBuf;
 use system_tray::client::Event;
 use system_tray::client::{ActivateRequest, UpdateEvent};
+use system_tray::item::IconPixmap;
 use tokio::sync::mpsc;
 use tracing::{debug, error, trace, warn};
-
```
Comment (JakeStanger) [inline src/modules/tray/mod.rs:19]: Please re-add the whitespace between lines that's been removed throughout this file

File: src/modules/tray/mod.rs [hunk 2]
```diff
@@ -378,23 +403,33 @@ fn on_update(
...
-                                error!("error loading icon: {e}");
-                                menu_item.show_label();
-                            }
+                        menu_item.icon_pixmap = icon_pixmap.clone();
+                        menu_item.set_icon_name(icon_name.clone());
+                        // Register a fresh picture and ensure a label widget exists,
+                        // then load the image asynchronously.
+                        let picture = Picture::builder()
+                            .content_fit(ContentFit::ScaleDown)
+                            .build();
```
Comment (JakeStanger) [inline src/modules/tray/mod.rs]: Why are we creating a new picture instead of using the existing one?

**Review by JakeStanger — CHANGES_REQUESTED** [review]

**Comment by pancakedevourer** [comment]
Here you go. Kakoune removed most of the whitespace when I saved the file, for some unbeknownst reason

**Comment by JakeStanger** [comment]
Looks like the build is failing due to a syntax error. If you get a chance in the next few days could you try and fix that please? If not I'll amend when I can - should be getting back into the swing of things

**Comment by pancakedevourer** [comment]
Sorry, I synced the repo and didn't see if it builds 😅. Should be good now

**Review by JakeStanger — APPROVED** [review]
Cool LGTM, thanks

**Comment by pancakedevourer** [comment]
No problem :D
