### PR TITLE
fix(image): restore scheme and run http fetch on tokio runtime

### LINKED ISSUE #1261: [Music] Remote mpris cover not loading
**Describe the bug**

Possibly related to #55. I play my music through a local [feishin](https://github.com/jeffvli/feishin) client with a mpv backend by connecting to my own self-hosted [navidrome](https://github.com/navidrome/navidrome) server. Apparently the link to cover art cannot be correctly parsed. The navidrome server is following the OpenSubsonic API Endpoint of [getCoverArt](https://opensubsonic.netlify.app/docs/endpoints/getcoverart/), which might be incompatible with current implementation?

Here's also the error log:

```
2025-11-26T08:14:07.988038Z  WARN ironbar::modules::music: 437: failed to parse image: <https://<my-navidrome-server>/rest/getCoverArt.view>?id=<redacted>&u=<redacted>&s=<redacted>&t=<redacted>&v=1.13.0&c=Feishin&size=300&_=2025-07-17T10:06:51.09733746Z
```

**To reproduce**

1. Add module `music`
2. Try to play music through Feishin server connected to a remote Navidrome server.
3. Cover Art cannot be displayed.

**Expected behavior**
The art should appear.

**System information:**
- Distro:: ArchLinux
- Compositor: Hyprland
- Ironbar version: 0.18.0-pre (AUR-git)

**Configuration**

<details><summary>Config</summary>

```
[[center]]
type = "music"
player_type = "mpris"
```

</details>

<details><summary>Styles</summary>

none

</details>

### PR DESCRIPTION
**Pull request by slowsage**
URL split on ':' strips scheme from input_name, causing parse failure.
reqwest requires tokio context, was called from glib async.
Use spawn + oneshot pattern to bridge tokio and glib.

Fixes #1261

### CODE REVIEW

File: src/image/provider.rs [hunk 1]
```diff
@@ -183,7 +183,10 @@ impl Provider {
                 input_name[2..].to_string(),
             ))),
             #[cfg(feature = "http")]
-            Some(_t @ ("http" | "https")) => input_name.parse().ok().map(ImageLocation::Remote),
+            Some(t @ ("http" | "https")) => format!("{t}:{input_name}")
+                .parse()
+                .ok()
+                .map(ImageLocation::Remote),
```
Comment (JakeStanger) [inline src/image/provider.rs]: Rather than formatting here, you should be able to use the original input string


```suggestion
            Some(t @ ("http" | "https")) => input.parse().ok().map(ImageLocation::Remote),
```

File: src/image/provider.rs [hunk 2]
```diff
@@ -286,19 +289,24 @@ impl Provider {
...
-                Texture::from_bytes(&bytes)
+                let (tx, rx) = tokio::sync::oneshot::channel();
+                let uri = uri.clone();
+                spawn(async move {
+                    let res = async {
+                        let res = reqwest::get(uri).await?;
+                        if res.status().is_success() {
+                            Ok(res.bytes().await?)
+                        } else {
+                            Err(Report::msg(format!("HTTP {}", res.status())))
```
Comment (JakeStanger) [inline src/image/provider.rs]: Let's just add a little more detail here so it's more obvious in logs what this refers to

```suggestion
                            Err(Report::msg(format!("error fetching remote image: HTTP {}", res.status())))
```
