### PR TITLE
Launcher pagination and label truncation options

### LINKED ISSUE #633: [Launcher] Items overflow offscreen
**Describe the bug**
When using Launcher module with `show_names` enabled, applications with long title names let ironbar go offscreen.

**To Reproduce**
1. Enable launcher module with `show_names`.
2. Open some applications, maybe a browser window with a webpage that includes a long title.
3. Your ironbar will start going off-screen

**Expected behavior**
Title name should be truncated at least, and if still overflows, module should be scrollable without resizing entirety of ironbar.

**System information:**
 - Distro: NixOS 24.05
- Compositor: labwc
 - Ironbar version: 0.15.1

**Configuration**
`anchor_to_edges` is set to `true`, and margins are added (200 on left & 200 right).
Some basic styling is also added.

### PR DESCRIPTION
**Pull request by JakeStanger**
Adds `page_size` option to launcher module. Adds truncation option to label module/widget.

Resolves #633

### CODE REVIEW

File: src/modules/launcher/pagination.rs [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+
+    controls_container: gtk::Box,
+    btn_fwd: Button,
+}
+
+impl Pagination {
+    pub fn new(container: &gtk::Box, page_size: usize, orientation: Orientation) -> Self {
+        let scroll_box = gtk::Box::new(orientation, 0);
+        let scroll_back = Button::builder().label("󰅁").sensitive(false).build();
+        let scroll_fwd = Button::builder().label("󰅂").sensitive(false).build();
```
Comment (JakeStanger) [inline src/modules/launcher/pagination.rs:19]: Icons need to be configurable

File: src/modules/launcher/pagination.rs [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+
+        scroll_box.add_class("scroll-box");
+        scroll_back.add_class("btn-back");
+        scroll_fwd.add_class("btn-forward");
```
Comment (JakeStanger) [inline src/modules/launcher/pagination.rs:23]: These need documenting
